In [1]:
#importing the necessary libraries
from pandas_datareader import data
import pandas as pd
import yfinance as yf
import yahoofinancials
import matplotlib.pyplot as plt

In [2]:
pip install pandas_datareader

Requirement already satisfied: pandas_datareader in /home/james/anaconda3/lib/python3.7/site-packages (0.7.0)
Requirement already satisfied: lxml in /home/james/anaconda3/lib/python3.7/site-packages (from pandas_datareader) (4.3.2)
Requirement already satisfied: pandas>=0.19.2 in /home/james/anaconda3/lib/python3.7/site-packages (from pandas_datareader) (0.24.2)
Requirement already satisfied: requests>=2.3.0 in /home/james/anaconda3/lib/python3.7/site-packages (from pandas_datareader) (2.21.0)
Requirement already satisfied: wrapt in /home/james/anaconda3/lib/python3.7/site-packages (from pandas_datareader) (1.11.1)
Requirement already satisfied: python-dateutil>=2.5.0 in /home/james/anaconda3/lib/python3.7/site-packages (from pandas>=0.19.2->pandas_datareader) (2.8.0)
Requirement already satisfied: pytz>=2011k in /home/james/anaconda3/lib/python3.7/site-packages (from pandas>=0.19.2->pandas_datareader) (2018.9)
Requirement already satisfied: numpy>=1.12.0 in /home/james/anaconda3/lib/python3.7/site-packages (from pandas>=0.19.2->pandas_datareader) (1.16.2)
Requirement already satisfied: idna<2.9,>=2.5 in /home/james/anaconda3/lib/python3.7/site-packages (from requests>=2.3.0->pandas_datareader) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /home/james/anaconda3/lib/python3.7/site-packages (from requests>=2.3.0->pandas_datareader) (2020.4.5.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/james/anaconda3/lib/python3.7/site-packages (from requests>=2.3.0->pandas_datareader) (3.0.4)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /home/james/anaconda3/lib/python3.7/site-packages (from requests>=2.3.0->pandas_datareader) (1.24.1)
Requirement already satisfied: six>=1.5 in /home/james/anaconda3/lib/python3.7/site-packages (from python-dateutil>=2.5.0->pandas>=0.19.2->pandas_datareader) (1.12.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
pip install yfinance --upgrade --no-cache-dir

Requirement already up-to-date: yfinance in /home/james/anaconda3/lib/python3.7/site-packages (0.1.54)
Requirement already satisfied, skipping upgrade: numpy>=1.15 in /home/james/anaconda3/lib/python3.7/site-packages (from yfinance) (1.16.2)
Requirement already satisfied, skipping upgrade: multitasking>=0.0.7 in /home/james/anaconda3/lib/python3.7/site-packages (from yfinance) (0.0.9)
Requirement already satisfied, skipping upgrade: pandas>=0.24 in /home/james/anaconda3/lib/python3.7/site-packages (from yfinance) (0.24.2)
Requirement already satisfied, skipping upgrade: requests>=2.20 in /home/james/anaconda3/lib/python3.7/site-packages (from yfinance) (2.21.0)
Requirement already satisfied, skipping upgrade: pytz>=2011k in /home/james/anaconda3/lib/python3.7/site-packages (from pandas>=0.24->yfinance) (2018.9)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.5.0 in /home/james/anaconda3/lib/python3.7/site-packages (from pandas>=0.24->yfinance) (2.8.0)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /home/james/anaconda3/lib/python3.7/site-packages (from requests>=2.20->yfinance) (2020.4.5.1)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /home/james/anaconda3/lib/python3.7/site-packages (from requests>=2.20->yfinance) (3.0.4)
Requirement already satisfied, skipping upgrade: urllib3<1.25,>=1.21.1 in /home/james/anaconda3/lib/python3.7/site-packages (from requests>=2.20->yfinance) (1.24.1)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in /home/james/anaconda3/lib/python3.7/site-packages (from requests>=2.20->yfinance) (2.8)
Requirement already satisfied, skipping upgrade: six>=1.5 in /home/james/anaconda3/lib/python3.7/site-packages (from python-dateutil>=2.5.0->pandas>=0.24->yfinance) (1.12.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
pip install yahoofinancials

Requirement already satisfied: yahoofinancials in /home/james/anaconda3/lib/python3.7/site-packages (1.5)
Requirement already satisfied: pytz in /home/james/anaconda3/lib/python3.7/site-packages (from yahoofinancials) (2018.9)
Requirement already satisfied: beautifulsoup4 in /home/james/anaconda3/lib/python3.7/site-packages (from yahoofinancials) (4.7.1)
Requirement already satisfied: soupsieve>=1.2 in /home/james/anaconda3/lib/python3.7/site-packages (from beautifulsoup4->yahoofinancials) (1.8)
Note: you may need to restart the kernel to use updated packages.

In [5]:
bse = yf.Ticker("BSE")
print(bse)

yfinance.Ticker object <BSE>

In [6]:
bse.history(period="max")#We want to preview how it has been performing.This is our population.

             Open   High    Low  Close  Volume  Dividends  Stock Splits
Date
2002-10-29   5.82   5.84   5.82   5.82   66300      0.000             0
2002-10-30   5.82   5.83   5.82   5.82   21300      0.000             0
2002-10-31   5.82   5.83   5.82   5.82   13500      0.000             0
2002-11-01   5.83   5.83   5.82   5.82    8200      0.000             0
2002-11-04   5.82   5.88   5.82   5.82   36800      0.000             0
2002-11-05   5.82   5.83   5.82   5.82   10700      0.000             0
2002-11-06   5.83   5.84   5.82   5.83   10500      0.000             0
2002-11-07   5.84   5.84   5.82   5.82   13500      0.000             0
2002-11-08   5.82   5.83   5.82   5.82    2300      0.000             0
2002-11-11   5.84   5.84   5.82   5.82     400      0.000             0
2002-11-12   5.84   5.84   5.82   5.82    5100      0.000             0
2002-11-13   5.83   5.83   5.82   5.82    7700      0.000             0
2002-11-14   5.82   5.83   5.82   5.82    5200      0.000             0
2002-11-15   5.82   5.82   5.82   5.82    7800      0.000             0
2002-11-18   5.84   5.84   5.84   5.84    7000      0.000             0
2002-11-19   5.82   5.82   5.82   5.82    2300      0.000             0
2002-11-20   5.82   5.82   5.82   5.82    1000      0.000             0
2002-11-21   5.82   5.82   5.82   5.82    2200      0.000             0
2002-11-22   5.82   5.82   5.82   5.82    3100      0.000             0
2002-11-25   5.82   5.83   5.82   5.83    5700      0.000             0
2002-11-26   5.82   5.83   5.82   5.82    8800      0.000             0
2002-11-27   5.83   5.83   5.82   5.82   12800      0.000             0
2002-11-29   5.83   5.83   5.83   5.83    1200      0.000             0
2002-12-02   5.82   5.83   5.82   5.82  211800      0.000             0
2002-12-03   5.82   5.82   5.82   5.82   10800      0.000             0
2002-12-04   5.82   5.82   5.82   5.82    9600      0.000             0
2002-12-05   5.82   5.82   5.82   5.82       0      0.000             0
2002-12-06   5.82   5.83   5.82   5.83    8700      0.000             0
2002-12-09   5.82   5.82   5.82   5.82    7500      0.000             0
2002-12-10   5.82   5.83   5.82   5.82   12100      0.000             0
...           ...    ...    ...    ...     ...        ...           ...
2020-03-09  13.80  13.80  13.66  13.70    8100      0.000             0
2020-03-10  13.66  13.73  13.03  13.53   13600      0.000             0
2020-03-11  13.64  13.64  12.94  13.16   23200      0.000             0
2020-03-12  13.07  13.07  12.03  12.32   22300      0.000             0
2020-03-13  12.43  12.60  12.39  12.49   15700      0.041             0
2020-03-16  12.21  12.21  11.97  12.21   21600      0.000             0
2020-03-17  12.25  12.25  12.03  12.18  193600      0.000             0
2020-03-18  11.32  11.56  10.81  11.21   17100      0.000             0
2020-03-19  10.71  10.78   9.97  10.66   60500      0.000             0
2020-03-20  10.96  11.42  10.66  10.67   82800      0.000             0
2020-03-23  10.82  10.82  10.37  10.53   22700      0.000             0
2020-03-24  10.61  11.03  10.60  11.00   39100      0.000             0
2020-03-25  10.92  11.85  10.92  11.85   23100      0.000             0
2020-03-26  12.06  12.36  11.96  12.32   21000      0.000             0
2020-03-27  12.26  12.46  12.12  12.26   10600      0.000             0
2020-03-30  12.43  12.53  12.34  12.53    7300      0.000             0
2020-03-31  12.52  12.54  12.46  12.46   14000      0.000             0
2020-04-01  12.46  12.46  12.02  12.15   42800      0.000             0
2020-04-02  12.13  12.13  11.97  11.97   15800      0.000             0
2020-04-03  11.88  11.93  11.66  11.67    6700      0.000             0
2020-04-06  11.78  12.00  11.78  11.90   14600      0.000             0
2020-04-07  11.95  12.17  11.95  12.17   21300      0.000             0
2020-04-08  12.11  12.43  12.11  12.27   20500      0.000             0
2020-04-09  12.59  12.63  12.44  12.44   12100      0.000             0
2020-04-13  12.51  12.53  12.36  12.37   20900      0.000             0
2020-04-14  12.40  12.57  12.40  12.51   40600      0.041             0
2020-04-15  12.48  12.52  12.45  12.50   25200      0.000             0
2020-04-16  12.45  12.53  12.45  12.48    6200      0.000             0
2020-04-17  12.47  12.49  12.35  12.46   10300      0.000             0
2020-04-20  12.51  12.46  12.35  12.40    4547      0.000             0

[4398 rows x 7 columns]

In [7]:
data = yf.download("BSE", start="2019-01-01", end="2019-12-31",
                   group_by="ticker")

[*********************100%***********************]  1 of 1 completed

In [8]:
# User pandas_reader.data.DataReader to load the desired data.
panel_data = data.DataReader('BSE','yahoo',start_date, end_date)

AttributeError: 'DataFrame' object has no attribute 'DataReader'

In [ ]:
# We would like all available data from "2019-01-01"until "2019-01-31".
start_date = '2019-01-01'
end_date = '2019-12-31'

In [ ]:

data.tail()

In [ ]:
data.head()

In [ ]:
data['Close'].plot(title="BSE's stock price")

In [ ]:
#the following codes executes different visualizations of the BSE stock prices upon request

In [ ]:
def histogram(data, n_bins, cumulative=False, x_label = "", y_label = "", title = ""):
    _, ax = plt.subplots()
    ax.hist(data, n_bins = n_bins, cumulative = cumulative, color = '#539caf')
    ax.set_ylabel(y_label)
    ax.set_xlabel(x_label)
    ax.set_title(title)
    plt.tight_layout()
plt.show()

In [ ]:
import matplotlib
matplotlib.axes.Axes.scatter
matplotlib.pyplot.scatter

In [ ]:
def scatterplot(x_data, y_data, x_label="", y_label="", title="", color = "r", yscale_log=False):

    # Create the plot object
    ax = plt.subplots()

    # Plot the data, set the size (s), color and transparency (alpha)
    # of the points
    ax.scatter(x_data, y_data, s = 10, color = color, alpha = 0.75)

    if yscale_log == True:
        ax.set_yscale('log')

    # Label the axes and provide a title
    ax.set_title(title)
    ax.set_xlabel(x_label)
    ax.set_ylabel(y_label)

In [ ]:
plt.subplots()

In [ ]:
def lineplot(x_data, y_data, x_label="", y_label="", title=""):
    # Create the plot object
    _, ax = plt.subplots()

    # Plot the best fit line, set the linewidth (lw), color and
    # transparency (alpha) of the line
    ax.plot(x_data, y_data, lw = 2, color = '#539caf', alpha = 1)

    # Label the axes and provide a title
    ax.set_title(title)
    ax.set_xlabel(x_label)
    ax.set_ylabel(y_label)

In [ ]:
def boxplot(x_data, y_data, base_color="#539caf", median_color="#297083", x_label="", y_label="", title=""):
    _, ax = plt.subplots()

    # Draw boxplots, specifying desired style
    ax.boxplot(y_data
               # patch_artist must be True to control box fill
               , patch_artist = True
               # Properties of median line
               , medianprops = {'color': median_color}
               # Properties of box
               , boxprops = {'color': base_color, 'facecolor': base_color}
               # Properties of whiskers
               , whiskerprops = {'color': base_color}
               # Properties of whisker caps
               , capprops = {'color': base_color})

    # By default, the tick label starts at 1 and increments by 1 for
    # each box drawn. This sets the labels to the ones we want
    ax.set_xticklabels(x_data)
    ax.set_ylabel(y_label)
    ax.set_xlabel(x_label)
    ax.set_title(title)

In [ ]:
def barplot(x_data, y_data, error_data, x_label="", y_label="", title=""):
    _, ax = plt.subplots()
    # Draw bars, position them in the center of the tick mark on the x-axis
    ax.bar(x_data, y_data, color = '#539caf', align = 'center')
    # Draw error bars to show standard deviation, set ls to 'none'
    # to remove line between points
    ax.errorbar(x_data, y_data, yerr = error_data, color = '#297083', ls = 'none', lw = 2, capthick = 2)
    ax.set_ylabel(y_label)
    ax.set_xlabel(x_label)
    ax.set_title(title)



def stackedbarplot(x_data, y_data_list, colors, y_data_names="", x_label="", y_label="", title=""):
    _, ax = plt.subplots()
    # Draw bars, one category at a time
    for i in range(0, len(y_data_list)):
        if i == 0:
            ax.bar(x_data, y_data_list[i], color = colors[i], align = 'center', label = y_data_names[i])
        else:
            # For each category after the first, the bottom of the
            # bar will be the top of the last category
            ax.bar(x_data, y_data_list[i], color = colors[i], bottom = y_data_list[i - 1], align = 'center', label = y_data_names[i])
    ax.set_ylabel(y_label)
    ax.set_xlabel(x_label)
    ax.set_title(title)
    ax.legend(loc = 'upper right')



def groupedbarplot(x_data, y_data_list, colors, y_data_names="", x_label="", y_label="", title=""):
    _, ax = plt.subplots()
    # Total width for all bars at one x location
    total_width = 0.8
    # Width of each individual bar
    ind_width = total_width / len(y_data_list)
    # This centers each cluster of bars about the x tick mark
    alteration = np.arange(-(total_width/2), total_width/2, ind_width)

    # Draw bars, one category at a time
    for i in range(0, len(y_data_list)):
        # Move the bar to the right on the x-axis so it doesn't
        # overlap with previously drawn ones
        ax.bar(x_data + alteration[i], y_data_list[i], color = colors[i], label = y_data_names[i], width = ind_width)
    ax.set_ylabel(y_label)
    ax.set_xlabel(x_label)
    ax.set_title(title)
    ax.legend(loc = 'upper right')